### PR TITLE
Add support for Prestaged Deployment Type

### PR DESCRIPTION
**Pull request by merlinfrombelgium**
In relation to https://github.com/MSEndpointMgr/ConfigMgr/pull/249

Added Prestaged DeploymentType and needed logic to support it.

The difference with BareMetal and PreCached modes, is that the Prestaged mode shares all logic with BareMetal, except for the download invocation. The package is downloaded to "%_SMSTSMediaRootPath%SMS\PKG" in order for the Task Sequence Manager to check if the driver package is included with the prestaged media (local disk) and whether or not the hash and content have changed since the prestaged media was created.

### CODE REVIEW

**Comment by merlinfrombelgium** [comment]
I didn't augment the version to 3.0.x because the first version to support Prestaged mode was 2.2.8 which was also committed today.

I'll leave the decision up to you whether or not you'd like to change timestamp and version.

**Comment by merlinfrombelgium** [comment]
Also fixed a few spelling mistakes highlighted by PSScriptAnalyzer. Spelling changes made to comment sections only, not to any of the script logic.

**Comment by merlinfrombelgium** [comment]
@NickolajA I take it you aim to add this functionality through a parameter `PreCacheDirectory`?
https://github.com/MSEndpointMgr/ModernDriverManagement/projects/1#card-42469462

**Comment by NickolajA** [comment]
By adding such a parameter and simply have the content downloaded to whatever path you desire, solve your scenario?

**Comment by merlinfrombelgium** [comment]
> By adding such a parameter and simply have the content downloaded to whatever path you desire, solve your scenario?

As I understand it, no it would not. The PreCache type only caches the drivers. The Baremetal deployment injects the drivers.
My scenario is a baremetal one, but using prestaged contents.

I would understand your reluctance to add complexity, but the only 2 changes here are an extra parameterset and an additional line in the Invoke-DownloadDriverPackageContent function.

**Pull request merged**
